export const questions = [
  { word: "____ libro", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ studente", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ albero", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ ragazzi", correct: "i", options: ["i","gli","le","un"] },
  { word: "____ amici", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ penna", correct: "la", options: ["la","il","le","uno"] },
  { word: "____ case", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ zaino", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ psicologo", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ yogurt", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ uomo", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ studenti bravi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ attore famoso", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ museo", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ orologio", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ sport", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ caffè", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ stadio", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ amici simpatici", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ insegnante", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ zii", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ scuole", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ fratello", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ sorella", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ bicchiere", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ specchio", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ gnomo", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ sci", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ studenti italiani", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ amici nuovi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ attrice", correct: "l'", options: ["la","il","l'","uno"] },
  { word: "____ insegnanti", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ università", correct: "l'", options: ["la","il","l'","uno"] },
  { word: "____ pizza", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ mele", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ macchina", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ tavolo", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ alberi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ bambini", correct: "i", options: ["i","gli","le","un"] },
  { word: "____ città", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ idee", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ giardino", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ giornale", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ zio", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ spettacolo", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ ombrello", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ amici allegri", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ occhi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ appartamento", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ studentesse", correct: "le", options: ["le", "gli", "i", "un"] },
  { word: "____ donne", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ madre", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ padre", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ vino", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ sportivo famoso", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ gnocchi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ spettacoli", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ studenti alti", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ strade", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ ferrovia", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ galleria", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ acqua", correct: "l'", options: ["la","il","l'","uno"] },
  { word: "____ amore", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ insegnante bravo", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ uomo alto", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ uomini simpatici", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ autobus", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ psicologi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ studenti universitari", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ porte", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ finestre", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ libro interessante", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ spettacolo teatrale", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ studente intelligente", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ scuola moderna", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ lingue", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ animale", correct: "l'", options: ["il","lo","l'","uno"] },
  { word: "____ fiume", correct: "il", options: ["il","lo","l'","uno"] },
  { word: "____ montagna", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ laghi", correct: "i", options: ["i","gli","le","un"] },
  { word: "____ amici italiani", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ fratelli", correct: "i", options: ["i","gli","le","un"] },
  { word: "____ sorelle", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ studenti americani", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ zaini", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ specchi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ psicologia", correct: "la", options: ["la","il","l'","uno"] },
  { word: "____ yogurt greco", correct: "lo", options: ["il","lo","l'","uno"] },
  { word: "____ università pubblica", correct: "l'", options: ["la","il","l'","uno"] },
  { word: "____ università private", correct: "le", options: ["le","gli","i","un"] },
  { word: "____ occhiali", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ amici buoni", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ amici sportivi", correct: "gli", options: ["i","gli","le","un"] },
  { word: "____ amici allegri", correct: "gli", options: ["i","gli","le","un"] },
];